export type CorsStatus = "yes" | "header" | "unknown" | "local";
export type Region = "global" | "cn" | "local" | "custom";

export interface ProviderPreset {
  id: string;
  name: string;
  /** Localised display name (zh-CN). Falls back to `name`. */
  nameZh?: string;
  region: Region;
  baseUrl: string;
  altBaseUrls?: { label: string; url: string }[];
  keysUrl?: string;
  docsUrl?: string;
  /** Header carrying the API key (default Authorization: Bearer). */
  authHeader?: string;
  authPrefix?: string;
  extraHeaders?: Record<string, string>;
  requiresKey: boolean;
  suggestedModels: string[];
  maxTokensParam: "max_tokens" | "max_completion_tokens";
  /** Whether the provider is known to answer browser (CORS) requests. */
  cors: CorsStatus;
  /** Reasoning dialect ids (see reasoning-dialects.ts) documented for this provider. */
  reasoningDialects: string[];
  notes?: { en: string; zh: string };
}

export const PROVIDER_PRESETS: ProviderPreset[] = [
  {
    id: "openai",
    name: "OpenAI",
    region: "global",
    baseUrl: "https://api.openai.com/v1",
    keysUrl: "https://platform.openai.com/api-keys",
    docsUrl: "https://platform.openai.com/docs/api-reference/chat",
    requiresKey: true,
    suggestedModels: ["gpt-5.1", "gpt-5", "gpt-5-mini", "gpt-5-nano", "gpt-4.1", "gpt-4.1-mini", "gpt-4o", "gpt-4o-mini", "o4-mini", "o3"],
    maxTokensParam: "max_completion_tokens",
    cors: "yes",
    reasoningDialects: ["reasoning_effort_none", "reasoning_effort_minimal"],
    notes: {
      en: "Reasoning models (o-series, GPT-5) reject `max_tokens`; use `max_completion_tokens`. `reasoning_effort: \"none\"` needs GPT-5.1 or newer.",
      zh: "推理模型（o 系列、GPT-5）不接受 `max_tokens`，需使用 `max_completion_tokens`。`reasoning_effort: \"none\"` 需要 GPT-5.1 及以上。",
    },
  },
  {
    id: "anthropic",
    name: "Anthropic (OpenAI-compatible)",
    nameZh: "Anthropic（OpenAI 兼容接口）",
    region: "global",
    baseUrl: "https://api.anthropic.com/v1",
    keysUrl: "https://console.anthropic.com/settings/keys",
    docsUrl: "https://docs.anthropic.com/en/api/openai-sdk",
    extraHeaders: { "anthropic-dangerous-direct-browser-access": "true" },
    requiresKey: true,
    suggestedModels: ["claude-sonnet-4-5", "claude-opus-4-1", "claude-haiku-4-5", "claude-sonnet-4"],
    maxTokensParam: "max_tokens",
    cors: "header",
    reasoningDialects: ["reasoning_effort_minimal", "thinking_type"],
    notes: {
      en: "Uses Anthropic's OpenAI SDK compatibility layer, which supports a subset of Chat Completions. Browser calls require the `anthropic-dangerous-direct-browser-access` header (added automatically).",
      zh: "使用 Anthropic 的 OpenAI SDK 兼容层，仅支持 Chat Completions 的子集。浏览器直连需要 `anthropic-dangerous-direct-browser-access` 请求头（已自动添加）。",
    },
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    region: "cn",
    baseUrl: "https://api.deepseek.com/v1",
    keysUrl: "https://platform.deepseek.com/api_keys",
    docsUrl: "https://api-docs.deepseek.com/",
    requiresKey: true,
    suggestedModels: ["deepseek-chat", "deepseek-reasoner"],
    maxTokensParam: "max_tokens",
    cors: "yes",
    reasoningDialects: ["thinking_type"],
    notes: {
      en: "`deepseek-chat` is the non-thinking mode and `deepseek-reasoner` the thinking mode of the same model. Prompt cache hits are reported as `prompt_cache_hit_tokens`.",
      zh: "`deepseek-chat` 为非思考模式，`deepseek-reasoner` 为思考模式。缓存命中通过 `prompt_cache_hit_tokens` 返回。",
    },
  },
  {
    id: "qwen",
    name: "Alibaba Qwen (Model Studio / DashScope)",
    nameZh: "阿里云百炼 · 通义千问 (DashScope)",
    region: "cn",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    altBaseUrls: [{ label: "International (Singapore)", url: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1" }],
    keysUrl: "https://bailian.console.aliyun.com/?apiKey=1#/api-key",
    docsUrl: "https://help.aliyun.com/zh/model-studio/compatibility-of-openai-with-dashscope",
    requiresKey: true,
    suggestedModels: ["qwen3-max", "qwen-plus", "qwen-flash", "qwen-turbo", "qwen3-235b-a22b", "qwen3-vl-plus", "qwen-vl-max", "qwq-plus"],
    maxTokensParam: "max_tokens",
    cors: "unknown",
    reasoningDialects: ["enable_thinking"],
    notes: {
      en: "Hybrid models (qwen-plus, qwen3-*) toggle thinking with `enable_thinking`. Some thinking configurations only work with streaming; the tester falls back to streaming automatically.",
      zh: "混合推理模型（qwen-plus、qwen3-*）通过 `enable_thinking` 开关思考。部分思考配置仅支持流式调用，测试器会自动回退到流式。",
    },
  },
  {
    id: "volcengine",
    name: "Volcengine Ark (Doubao)",
    nameZh: "火山方舟 · 豆包 (Volcengine Ark)",
    region: "cn",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    altBaseUrls: [{ label: "BytePlus (international)", url: "https://ark.ap-southeast.bytepluses.com/api/v3" }],
    keysUrl: "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
    docsUrl: "https://www.volcengine.com/docs/82379/1298454",
    requiresKey: true,
    suggestedModels: ["doubao-seed-1-6-250615", "doubao-seed-1-6-thinking-250715", "doubao-seed-1-6-flash-250615", "doubao-1-5-pro-32k-250115", "deepseek-v3-250324", "kimi-k2-250711"],
    maxTokensParam: "max_tokens",
    cors: "unknown",
    reasoningDialects: ["thinking_type"],
    notes: {
      en: "Use a model ID or an endpoint ID (ep-…). Doubao Seed 1.6 toggles thinking with `thinking: {type: \"enabled\" | \"disabled\" | \"auto\"}`.",
      zh: "可填写模型 ID 或推理接入点 ID（ep-…）。豆包 Seed 1.6 通过 `thinking: {type: \"enabled\" | \"disabled\" | \"auto\"}` 控制思考。",
    },
  },
  {
    id: "minimax",
    name: "MiniMax",
    region: "cn",
    baseUrl: "https://api.minimaxi.com/v1",
    altBaseUrls: [{ label: "International", url: "https://api.minimax.io/v1" }],
    keysUrl: "https://platform.minimaxi.com/user-center/basic-information/interface-key",
    docsUrl: "https://platform.minimaxi.com/document/ChatCompletion",
    requiresKey: true,
    suggestedModels: ["MiniMax-M2", "MiniMax-M1", "MiniMax-Text-01"],
    maxTokensParam: "max_tokens",
    cors: "unknown",
    reasoningDialects: [],
    notes: {
      en: "MiniMax-M2 returns its reasoning inside `<think>…</think>` tags in the content; the tester separates it automatically.",
      zh: "MiniMax-M2 的思考内容以 `<think>…</think>` 标签内嵌在 content 中，测试器会自动拆分。",
    },
  },
  {
    id: "zhipu",
    name: "Zhipu AI (GLM)",
    nameZh: "智谱 AI · GLM",
    region: "cn",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    altBaseUrls: [{ label: "Z.ai (international)", url: "https://api.z.ai/api/paas/v4" }],
    keysUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    docsUrl: "https://docs.bigmodel.cn/cn/guide/develop/openai/introduction",
    requiresKey: true,
    suggestedModels: ["glm-4.6", "glm-4.5", "glm-4.5-air", "glm-4.5-flash", "glm-4.5v", "glm-4-plus", "glm-4-flash"],
    maxTokensParam: "max_tokens",
    cors: "unknown",
    reasoningDialects: ["thinking_type"],
  },
  {
    id: "moonshot",
    name: "Moonshot AI (Kimi)",
    nameZh: "月之暗面 · Kimi",
    region: "cn",
    baseUrl: "https://api.moonshot.cn/v1",
    altBaseUrls: [{ label: "International", url: "https://api.moonshot.ai/v1" }],
    keysUrl: "https://platform.moonshot.cn/console/api-keys",
    docsUrl: "https://platform.moonshot.cn/docs/api/chat",
    requiresKey: true,
    suggestedModels: ["kimi-k2-0905-preview", "kimi-k2-turbo-preview", "kimi-k2-thinking", "moonshot-v1-8k", "moonshot-v1-128k-vision-preview"],
    maxTokensParam: "max_tokens",
    cors: "unknown",
    reasoningDialects: ["thinking_type"],
  },
  {
    id: "baidu",
    name: "Baidu Qianfan (ERNIE)",
    nameZh: "百度千帆 · 文心",
    region: "cn",
    baseUrl: "https://qianfan.baidubce.com/v2",
    keysUrl: "https://console.bce.baidu.com/iam/#/iam/apikey/list",
    docsUrl: "https://cloud.baidu.com/doc/qianfan-api/s/Wm7lgvgdb",
    requiresKey: true,
    suggestedModels: ["ernie-4.5-turbo-128k", "ernie-x1-turbo-32k", "ernie-4.5-8k-preview", "deepseek-v3.1"],
    maxTokensParam: "max_completion_tokens",
    cors: "unknown",
    reasoningDialects: ["enable_thinking"],
  },
  {
    id: "tencent",
    name: "Tencent Hunyuan",
    nameZh: "腾讯混元",
    region: "cn",
    baseUrl: "https://api.hunyuan.cloud.tencent.com/v1",
    keysUrl: "https://console.cloud.tencent.com/hunyuan/api-key",
    docsUrl: "https://cloud.tencent.com/document/product/1729/111007",
    requiresKey: true,
    suggestedModels: ["hunyuan-turbos-latest", "hunyuan-t1-latest", "hunyuan-a13b", "hunyuan-lite"],
    maxTokensParam: "max_tokens",
    cors: "unknown",
    reasoningDialects: ["enable_thinking"],
  },
  {
    id: "stepfun",
    name: "StepFun",
    nameZh: "阶跃星辰",
    region: "cn",
    baseUrl: "https://api.stepfun.com/v1",
    keysUrl: "https://platform.stepfun.com/interface-key",
    docsUrl: "https://platform.stepfun.com/docs/api-reference/chat",
    requiresKey: true,
    suggestedModels: ["step-3", "step-2-16k", "step-1o-turbo-vision"],
    maxTokensParam: "max_tokens",
    cors: "unknown",
    reasoningDialects: [],
  },
  {
    id: "siliconflow",
    name: "SiliconFlow",
    nameZh: "硅基流动 SiliconFlow",
    region: "cn",
    baseUrl: "https://api.siliconflow.cn/v1",
    altBaseUrls: [{ label: "International", url: "https://api.siliconflow.com/v1" }],
    keysUrl: "https://cloud.siliconflow.cn/account/ak",
    docsUrl: "https://docs.siliconflow.cn/cn/api-reference/chat-completions/chat-completions",
    requiresKey: true,
    suggestedModels: ["Qwen/Qwen3-235B-A22B", "deepseek-ai/DeepSeek-V3.1", "deepseek-ai/DeepSeek-R1", "moonshotai/Kimi-K2-Instruct", "zai-org/GLM-4.5", "Qwen/Qwen2.5-VL-72B-Instruct"],
    maxTokensParam: "max_tokens",
    cors: "unknown",
    reasoningDialects: ["enable_thinking"],
  },
  {
    id: "gemini",
    name: "Google Gemini (OpenAI-compatible)",
    nameZh: "Google Gemini（OpenAI 兼容接口）",
    region: "global",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    keysUrl: "https://aistudio.google.com/apikey",
    docsUrl: "https://ai.google.dev/gemini-api/docs/openai",
    requiresKey: true,
    suggestedModels: ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.5-flash-lite", "gemini-2.0-flash"],
    maxTokensParam: "max_tokens",
    cors: "yes",
    reasoningDialects: ["reasoning_effort_none", "gemini_thinking_budget"],
  },
  {
    id: "xai",
    name: "xAI (Grok)",
    region: "global",
    baseUrl: "https://api.x.ai/v1",
    keysUrl: "https://console.x.ai/",
    docsUrl: "https://docs.x.ai/docs/api-reference",
    requiresKey: true,
    suggestedModels: ["grok-4", "grok-4-fast-reasoning", "grok-4-fast-non-reasoning", "grok-3", "grok-3-mini"],
    maxTokensParam: "max_tokens",
    cors: "yes",
    reasoningDialects: ["reasoning_effort_none"],
  },
  {
    id: "mistral",
    name: "Mistral AI",
    region: "global",
    baseUrl: "https://api.mistral.ai/v1",
    keysUrl: "https://console.mistral.ai/api-keys",
    docsUrl: "https://docs.mistral.ai/api/",
    requiresKey: true,
    suggestedModels: ["mistral-large-latest", "mistral-medium-latest", "mistral-small-latest", "magistral-medium-latest", "magistral-small-latest", "pixtral-large-latest", "codestral-latest"],
    maxTokensParam: "max_tokens",
    cors: "yes",
    reasoningDialects: [],
  },
  {
    id: "groq",
    name: "Groq",
    region: "global",
    baseUrl: "https://api.groq.com/openai/v1",
    keysUrl: "https://console.groq.com/keys",
    docsUrl: "https://console.groq.com/docs/openai",
    requiresKey: true,
    suggestedModels: ["llama-3.3-70b-versatile", "openai/gpt-oss-120b", "openai/gpt-oss-20b", "qwen/qwen3-32b", "meta-llama/llama-4-scout-17b-16e-instruct", "moonshotai/kimi-k2-instruct-0905"],
    maxTokensParam: "max_completion_tokens",
    cors: "yes",
    reasoningDialects: ["reasoning_effort_none"],
  },
  {
    id: "cerebras",
    name: "Cerebras",
    region: "global",
    baseUrl: "https://api.cerebras.ai/v1",
    keysUrl: "https://cloud.cerebras.ai/",
    docsUrl: "https://inference-docs.cerebras.ai/",
    requiresKey: true,
    suggestedModels: ["llama-3.3-70b", "gpt-oss-120b", "qwen-3-235b-a22b-instruct-2507", "qwen-3-32b"],
    maxTokensParam: "max_completion_tokens",
    cors: "yes",
    reasoningDialects: ["reasoning_effort_none"],
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    region: "global",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    keysUrl: "https://fireworks.ai/settings/users/api-keys",
    docsUrl: "https://docs.fireworks.ai/api-reference/post-chatcompletions",
    requiresKey: true,
    suggestedModels: ["accounts/fireworks/models/deepseek-v3p1", "accounts/fireworks/models/kimi-k2-instruct-0905", "accounts/fireworks/models/qwen3-235b-a22b-instruct-2507", "accounts/fireworks/models/gpt-oss-120b"],
    maxTokensParam: "max_tokens",
    cors: "yes",
    reasoningDialects: ["reasoning_effort_none"],
  },
  {
    id: "together",
    name: "Together AI",
    region: "global",
    baseUrl: "https://api.together.xyz/v1",
    keysUrl: "https://api.together.ai/settings/api-keys",
    docsUrl: "https://docs.together.ai/reference/chat-completions-1",
    requiresKey: true,
    suggestedModels: ["meta-llama/Llama-3.3-70B-Instruct-Turbo", "Qwen/Qwen3-235B-A22B-fp8-tput", "deepseek-ai/DeepSeek-V3.1", "moonshotai/Kimi-K2-Instruct-0905"],
    maxTokensParam: "max_tokens",
    cors: "yes",
    reasoningDialects: [],
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    region: "global",
    baseUrl: "https://openrouter.ai/api/v1",
    keysUrl: "https://openrouter.ai/keys",
    docsUrl: "https://openrouter.ai/docs/api-reference/chat-completion",
    requiresKey: true,
    suggestedModels: ["openai/gpt-5", "anthropic/claude-sonnet-4.5", "google/gemini-2.5-flash", "deepseek/deepseek-chat-v3.1", "qwen/qwen3-235b-a22b", "x-ai/grok-4", "moonshotai/kimi-k2-0905"],
    maxTokensParam: "max_tokens",
    cors: "yes",
    reasoningDialects: ["openrouter_reasoning", "reasoning_effort_none"],
    notes: {
      en: "OpenRouter normalises reasoning to `reasoning: { effort | max_tokens | exclude | enabled }` and exposes it as `reasoning` in the response.",
      zh: "OpenRouter 将推理参数统一为 `reasoning: { effort | max_tokens | exclude | enabled }`，响应中以 `reasoning` 字段返回。",
    },
  },
  {
    id: "azure",
    name: "Azure OpenAI (v1 API)",
    region: "global",
    baseUrl: "https://YOUR-RESOURCE.openai.azure.com/openai/v1",
    keysUrl: "https://portal.azure.com/",
    docsUrl: "https://learn.microsoft.com/azure/ai-foundry/openai/api-version-lifecycle",
    authHeader: "api-key",
    authPrefix: "",
    requiresKey: true,
    suggestedModels: ["gpt-4.1", "gpt-4o", "gpt-5"],
    maxTokensParam: "max_completion_tokens",
    cors: "unknown",
    reasoningDialects: ["reasoning_effort_none", "reasoning_effort_minimal"],
    notes: {
      en: "Replace YOUR-RESOURCE with your Azure resource name. The v1 API accepts either `api-key` or `Authorization: Bearer` and uses deployment names as model IDs.",
      zh: "将 YOUR-RESOURCE 替换为你的 Azure 资源名。v1 API 支持 `api-key` 或 `Authorization: Bearer`，模型 ID 填写部署名称。",
    },
  },
  {
    id: "ollama",
    name: "Ollama (local)",
    nameZh: "Ollama（本地）",
    region: "local",
    baseUrl: "http://localhost:11434/v1",
    docsUrl: "https://github.com/ollama/ollama/blob/main/docs/openai.md",
    requiresKey: false,
    suggestedModels: ["qwen3", "llama3.1", "gpt-oss:20b", "gemma3", "deepseek-r1"],
    maxTokensParam: "max_tokens",
    cors: "local",
    reasoningDialects: ["ollama_think", "chat_template_kwargs"],
    notes: {
      en: "Start Ollama with `OLLAMA_ORIGINS=\"*\"` (or this site's origin) so the browser is allowed to call it.",
      zh: "启动 Ollama 时设置 `OLLAMA_ORIGINS=\"*\"`（或本站域名），否则浏览器请求会被 CORS 拦截。",
    },
  },
  {
    id: "lmstudio",
    name: "LM Studio (local)",
    nameZh: "LM Studio（本地）",
    region: "local",
    baseUrl: "http://localhost:1234/v1",
    docsUrl: "https://lmstudio.ai/docs/app/api/endpoints/openai",
    requiresKey: false,
    suggestedModels: [],
    maxTokensParam: "max_tokens",
    cors: "local",
    reasoningDialects: ["chat_template_kwargs"],
    notes: {
      en: "Enable \"CORS\" in LM Studio → Developer → Server settings.",
      zh: "在 LM Studio → Developer → Server 设置中开启 CORS。",
    },
  },
  {
    id: "vllm",
    name: "vLLM / SGLang (self-hosted)",
    nameZh: "vLLM / SGLang（自建）",
    region: "local",
    baseUrl: "http://localhost:8000/v1",
    docsUrl: "https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html",
    requiresKey: false,
    suggestedModels: [],
    maxTokensParam: "max_tokens",
    cors: "local",
    reasoningDialects: ["chat_template_kwargs", "enable_thinking"],
    notes: {
      en: "Start vLLM with `--allowed-origins '[\"*\"]'` (SGLang: `--allow-origin`) to accept browser requests.",
      zh: "启动 vLLM 时加 `--allowed-origins '[\"*\"]'`（SGLang：`--allow-origin`）以允许浏览器请求。",
    },
  },
  {
    id: "custom",
    name: "Custom (OpenAI-compatible)",
    nameZh: "自定义（OpenAI 兼容）",
    region: "custom",
    baseUrl: "",
    requiresKey: false,
    suggestedModels: [],
    maxTokensParam: "max_tokens",
    cors: "unknown",
    reasoningDialects: [],
    notes: {
      en: "Any endpoint implementing POST {baseUrl}/chat/completions. Gateways such as LiteLLM, One API / New API, Portkey and Cloudflare AI Gateway work here.",
      zh: "任何实现了 POST {baseUrl}/chat/completions 的服务，例如 LiteLLM、One API / New API、Portkey、Cloudflare AI Gateway 等网关。",
    },
  },
];

export const PRESET_MAP: Record<string, ProviderPreset> = Object.fromEntries(PROVIDER_PRESETS.map((p) => [p.id, p]));

export function getPreset(id: string): ProviderPreset {
  return PRESET_MAP[id] ?? PRESET_MAP.custom;
}
